Migrate Manifest model from schematics to pydantic
hCaptcha/hmt-basemodels pull request #44
Opened 2020-09-05 16:09 UTC by hhio618

2020-09-06 07:45 UTC, uivlis commented
Hey @hhio618 thanks for your work! Be sure though to add pydantic or other dependencies in the Pipfile via `pipenv install pydantic --pre`. Also, please run `./bin/ci` on your local machine after your changes to test if everything is ok; as you can see right now, the CI tests are failing.

2020-09-06 14:32 UTC, hhio618 commented
Hey @uivlis thank you for your hints. I just updated the code and all checks have been passed.

2020-09-07 23:19 UTC, uivlis commented
Thanks @hhio618 for that, waiting now for @gaieges to add his review and we should be good to go.

2020-09-08 13:35 UTC, gaieges requested changes
Need to add pydantic to the setup.py

Also needs some readme content on how to use both of the libraries (ie how to select pydantic, how to select schematic). 

For now we should also maintain support for schematics being the primary model to support backward compatibility.  I'd also up the minor version as well, since we're not fully cutting over to pydantic yet.  Next step might be to do a major version upgrade and migrate other clients over to it, and maintain support for old version in a previous branch

Good idea around the testing approach though!

2020-09-08 13:35 UTC, gaieges commented on test.py
> +SCHEMATICS = "shematics"
typo

2020-09-08 15:17 UTC, gaieges commented
Chatted with our team a bit more about this - I think we want to take the approach of keeping old schematics models in their existing place, and pydantic models in a new module / namespace so that clients can opt in to.  So this would be a minor semver update in the setup.py

2020-09-08 17:32 UTC, hhio618 commented
Hi @gaieges, thank you for the review. I just updated the code.

2020-09-09 20:42 UTC, gaieges reviewed
I think this looks great, one additional note around version. I want to have @alexeysofin and @Villux take a quick pass at this too

2020-09-10 07:40 UTC, hhio618 commented on setup.py
> +    install_requires=[
I changed the version number to **0.1.0**. Do I need to upgrade dependencies too?

2020-09-10 13:34 UTC, alexeysofin approved these changes

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    job_id: UUID = uuid.uuid4()
Are you sure that default must be set on class level? `job_id` will be the same for all future instances

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/data/groundtruth.py
> +def validate_wrapper_model(Model, data):
Why use validate functions instead of just instantiating a model class with values?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/data/groundtruth.py
> +    entity_name: Union[int, float]
I think float type will include integer by casting any int to float? can't just use `entity_name: float`?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/data/groundtruth.py
> +ILASGroundtruthEntryModel = create_wrapper_model(ilas_groundtruth_entry_type)
I believe https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types maybe be helpful here to make a model with unknown root keys, but maybe I am wrong

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/data/taskdata.py
> +class AtLeastTenCharUrl(HttpUrl):
Isn't this supposed to be a validator?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    if "taskdata" in values and values['taskdata'] is not None and \
I believe values['taskdata'] can be changed to `taskdata = values.get('taskdata')` on a separate line to avoid hashing three times?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +            if multi_challenge == False:
maybe `if not multi_challenge` ?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +            if not "multi_challenge_manifests" in values:
I believe `if "multi_challenge_manifests" not in values` is more readable :)

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +        if value == BaseJobTypesEnum.multi_challenge:
Are you sure that `value` will be already cast to enum here? Just wondering

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    shape_type: Optional[Literal['point', 'bounding_box', 'polygon']]
Isn't this supposed to be enum?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    exchange: Optional[Dict[str, Union[str, int, float]]]
All fields Optional?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    validate_request_type = validator('request_type', allow_reuse=True, \
Sure you don't want a base class with a method?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +        json_encoders = {
I believe pydantic is able to encode uuid by default, no?

2020-09-10 13:34 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +        if not ("request_type" in values):
maybe `if "request_type" not in values` ?

2020-09-10 19:50 UTC, hhio618 commented on basemodels/pydantic/manifest/data/groundtruth.py
> +def validate_wrapper_model(Model, data):
Yeah, sure. I will fix this then.

2020-09-10 20:00 UTC, hhio618 commented on basemodels/pydantic/manifest/manifest.py
> +        if value == BaseJobTypesEnum.multi_challenge:
Yeah, actually I tested this and the type of the value is <enum 'BaseJobTypesEnum'>!

2020-09-10 20:13 UTC, hhio618 commented on basemodels/pydantic/manifest/manifest.py
> +    exchange: Optional[Dict[str, Union[str, int, float]]]
The original model (based on schematics library) didn't mentioned that this fields need to be required. And I'm pretty sure that all fields are required=False by default in the schematics library, So I kept them that way!

2020-09-10 20:17 UTC, hhio618 commented on basemodels/pydantic/manifest/manifest.py
> +    job_id: UUID = uuid.uuid4()
Yeah actually this is my mistake, and I should set the default in a validator function.

2020-09-10 20:27 UTC, e271828- commented on basemodels/pydantic/manifest/manifest.py
> +    exchange: Optional[Dict[str, Union[str, int, float]]]
Yes, this field is entirely optional.

2020-09-10 20:54 UTC, alexeysofin commented on basemodels/pydantic/manifest/manifest.py
> +    exchange: Optional[Dict[str, Union[str, int, float]]]
@e271828- I mean all fields in `InternalConfig` are Optional, if that's ok

2020-09-10 21:15 UTC, gaieges commented on setup.py
> +    install_requires=[
Only if you need to upgrade deps, `0.1.0` sounds good

2020-09-11 12:56 UTC, hhio618 commented on basemodels/pydantic/manifest/manifest.py
> +            entries_count = traverse_json_entries(response.json(), validate_entry)
I copied this part of the code from "basemodels/manifest/manifest.py". I just tried to use a strict model but there are some cases where exact responses schemas are unknown for groundtruth_uri (could be either of dict or list!)

2020-09-11 17:59 UTC, gaieges commented on basemodels/pydantic/manifest/__init__.py
> +from .manifest import *
Yeah good idea, we should generally avoid `import *`

2020-09-11 22:40 UTC, gaieges approved these changes
Gtg from my perspective.  We'll have to tag the bumped version once merged

2020-09-12 07:57 UTC, hhio618 commented on basemodels/pydantic/manifest/data/groundtruth.py
> +GroundtruthEntryKeyModel = create_wrapper_model(groundtruth_entry_key_type)
From the pydantic docs: "Pydantic supports the creation of generic models to make it easier to reuse a common model structure.". but that needs a python version > 3.7. another option here could be dynamic model creation (https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation)

2020-09-12 08:06 UTC, hhio618 commented on basemodels/pydantic/manifest/data/groundtruth.py
> +ILASGroundtruthEntryModel = create_wrapper_model(ilas_groundtruth_entry_type)
Thanks, seems good. So make a class for each of the four models using root types will be a good idea?

2020-09-14 18:21 UTC, gaieges commented
Waiting on anything here?

2020-09-15 05:38 UTC, hhio618 commented
Is there anything else that I can do?

2020-09-15 05:50 UTC, hhio618 commented
I think it's ready to be merged. please let me know if anything else we need here.

2020-09-15 08:10 UTC, uivlis commented
@hhio618 Thanks, again, for your work! I was just trying to accept your submission, I'm having issues with gitcoin, and you're not alone, a recent contributor got his eth, eventually, but the submission was not recorded. You should receive soon a Kudos from https://etherscan.io/tx/0xe306b0e9dec5248b8eb66d11ab841012f8cdffd818d1193ab1cec0a33ab376e5, and then I'll be able to payout this bounty. Let me kindly apologize for this inconvenience, I paid 20$ in gas costs and it's still taking more than 1 hour to submit!

2020-09-15 16:22 UTC, hhio618 commented
You're welcome. I'm very glad I was able to help. Sorry to hear that you have difficulties with Gitcoin. Thank you for the Kudos and the payout (I really liked the Kudos :) ).

2020-09-15 19:06 UTC, merged