Feature/53
hCaptcha/hmt-basemodels pull request #54
Opened 2021-05-31 18:58 UTC by rodriguez-facundo

Add metadata field to taskdata entry

2021-06-01 06:27 UTC, Villux requested changes

2021-06-01 06:27 UTC, Villux commented on basemodels/pydantic/manifest/data/taskdata.py
> +        if any(len(str(v)) > 255 for v in value.values()):
Why we have key and value length limit?

2021-06-01 13:30 UTC, rodriguez-facundo commented on basemodels/pydantic/manifest/data/taskdata.py
> +        if any(len(str(v)) > 255 for v in value.values()):
Could remove it. Mainly to prevent very big taskdata that is slow to pull/parse and eats up memory. But I don't think is a very big problem.

2021-06-01 16:01 UTC, gaieges commented on basemodels/pydantic/manifest/data/taskdata.py
> +        if any(len(str(v)) > 255 for v in value.values()):
Yeah i’d keep this so people don’t go crazy with it. these files are already fairly large

2021-06-01 16:02 UTC, gaieges commented
Might want to also allow int/float values

2021-06-01 21:23 UTC, e271828- approved these changes

2021-06-01 21:35 UTC, e271828- commented
@rodriguez-facundo One additional enforcement I'd suggest is to limit `len(str(metadata)) <= 1024`.

2021-06-02 06:38 UTC, Villux commented
MITL has model uri in metadata for now. I'm just worried that we might need to add something else there as well if additional data related to the images need to be store for the training

2021-06-02 06:42 UTC, Villux commented
Just a thing that I have realized now is that most likely json format was not a good pick from us. Maybe it would have been better to use first line of the file for job related stuff and then the following lines would be the datapoints. This would enable us to read files without huge memory load. We actually haven't done any massive datasets yet so we don't know the limits. With mitl we have used 100-200k tasks only.

2021-06-02 15:14 UTC, gaieges commented
I agree, but luckily this isn't something that needs to be _super_ fast.  I can imagine us adding a parquet "dataset" format down the road with a similar data format for input

2021-06-03 03:13 UTC, e271828- commented
> Just a thing that I have realized now is that most likely json format was not a good pick from us. Maybe it would have been better to use first line of the file for job related stuff and then the following lines would be the datapoints. This would enable us to read files without huge memory load. We actually haven't done any massive datasets yet so we don't know the limits. With mitl we have used 100-200k tasks only.

This is an external interchange format; nothing prevents the internal format from being an AVRO or similar, especially with a versioned schema for the JSON.

2021-06-04 15:13 UTC, rodriguez-facundo commented
Would it be ok to merge @Villux?

2021-06-07 07:13 UTC, Villux commented
ok for me!

2021-06-07 13:11 UTC, rodriguez-facundo commented
Could you give me approval @Villux? The pr got blocked by "change requested"

2021-06-07 14:27 UTC, Villux approved these changes

2021-06-07 14:28 UTC, Villux commented
sorry about that. Didn't realize I was blocking it

2021-06-09 12:38 UTC, merged