feat: adding field to support storing final results publicly
hCaptcha/hmt-basemodels pull request #80
Opened 2022-08-03 17:59 UTC by hugoseabra-imachines

Adding field `store_pub_final_results` in Manifest model to support this option to store final results when not encrypted.

IMI-2282

2022-08-03 20:26 UTC, DicksonChi commented on basemodels/manifest/manifest.py
> +    store_pub_final_results = BooleanType(default=False,)
The default for BooleanType is already False no need to add that

2022-08-03 21:56 UTC, hugoseabra-imachines commented on basemodels/manifest/manifest.py
> +    store_pub_final_results = BooleanType(default=False,)
I also thought so. But checking the `BooleanType` class, there is nothing to determine a default value. Check [this](https://github.com/schematics/schematics/blob/master/schematics/types/base.py#L598). So, if nothing is passed, the default value will be `None`, which is not acceptable.

2022-08-04 09:42 UTC, DicksonChi commented on basemodels/manifest/manifest.py
> +    store_pub_final_results = BooleanType(default=False,)
yes you are right!

2022-08-04 09:42 UTC, DicksonChi approved these changes
LGTM

2022-08-04 12:40 UTC, e271828- requested changes
Please rename to `public_results`

2022-08-09 16:18 UTC, spirit-q2 commented
I still don't understand why exactly we want this as a new DB field and not as the manifest key... 🤔
can you remind me of the reason?

cc @igervasiychuk

2022-08-09 16:18 UTC, spirit-q2 commented on basemodels/manifest/manifest.py
> +    public_results = BooleanType(default=False,)
I still don't understand why exactly we want this as a new DB field and not as the manifest key... 🤔
can you remind me of the reason?

cc @igervasiychuk

2022-08-09 16:28 UTC, igervasiychuk commented on basemodels/manifest/manifest.py
> +    public_results = BooleanType(default=False,)
the reasoning was that it **is** a manifest key, but we also copy the most important fields into columns. And that makes access to them easier downstream (you can look at other relevant PRs).

2022-08-10 12:06 UTC, DicksonChi approved these changes
LGTM

2022-08-10 12:28 UTC, e271828- approved these changes

2022-08-10 12:37 UTC, merged