Validating image from URI
hCaptcha/hmt-basemodels pull request #81
Opened 2022-08-31 00:18 UTC by hugoseabra-imachines

Validation whether a given URI in `datapoint_uri` has a valid image.

IMI-4164

2022-08-31 08:21 UTC, igervasiychuk requested changes

2022-08-31 08:21 UTC, igervasiychuk commented on basemodels/pydantic/utils.py
> +def check_valid_image(name: str, uri: str) -> None:
there seem to be two copy of this func?

2022-08-31 08:21 UTC, igervasiychuk commented on basemodels/manifest/data/taskdata.py
> +    check_valid_image(str(task_data.task_key), str(task_data.datapoint_uri))
this would validate **every** image, we need just one

2022-08-31 08:21 UTC, igervasiychuk commented on basemodels/manifest/utils.py
> +        image_formats = ("image/png", "image/jpeg", "image/jpg")
this doesn't make sense here (just three values), but in general, it'd be nice for it to be a set

2022-08-31 08:21 UTC, igervasiychuk commented on basemodels/manifest/utils.py
> +        if 'content-type' in r.headers and r.headers["content-type"] not in image_formats:
may be r.headers('content-type','') not in ....
also, inconsistent quote symbols (' and " in one line)

2022-08-31 08:21 UTC, igervasiychuk commented on tests/test_utils.py
> +    check_valid_image as pydanticImageChecker,
unclear: 
why rename it
why a function is camelCase

2022-09-02 14:35 UTC, igervasiychuk requested changes

2022-09-02 14:35 UTC, igervasiychuk commented on basemodels/manifest/manifest.py
> +    only_sign_results = BooleanType(default=False, )
can we remove ", "

2022-09-06 09:27 UTC, igervasiychuk reviewed
pls test it in our env

2022-09-06 10:07 UTC, igervasiychuk commented
+ Will that work with text challenges

2022-09-06 11:32 UTC, igervasiychuk commented
also, will that work with taskdata, and groundtruth? (not just taskdata_uri, groundtruth_uri)

2022-09-06 18:46 UTC, e271828- commented on basemodels/manifest/manifest.py
> +            data = response.json()
This needs to be rethought. You're loading a potentially gigantic file into memory with no safeguards. Maybe cap it to first 100KB.

2022-09-13 11:44 UTC, igervasiychuk commented
don't forget to bump the version

2023-06-09 18:11 UTC, closed without merging