[IMI-4164] Add content type image validation for supported jobs
hCaptcha/hmt-basemodels pull request #82
Opened 2022-09-27 10:19 UTC by WalrusB

2022-09-27 10:21 UTC, WalrusB commented on tests/both_models.py
> +    # TODO: FINISH THIS TEST
Mock patch doesn't seem to work properly here I'll take a look and fix this test while the rest of the task is in review.

2022-09-27 13:57 UTC, igervasiychuk requested changes
so with a current poetry.toml/poetry.lock, both_models fail with "AttributeError: 'Manifest' object has no attribute 'store_pub_final_results'" 

otherwise, code is very reasonable

2022-09-28 07:48 UTC, alidzm requested changes

2022-09-28 07:48 UTC, alidzm commented on basemodels/pydantic/manifest/data/groundtruth.py
> +SUPPORTED_CONTENT_TYPES = [
Could constants and functions be moved to any shared folder, because we have equal `SUPPORTED_CONTENT_TYPES`, `validate_content_type`, `JOB_TYPES_FOR_CONTENT_TYPE_VALIDATION` for manifest and pydantic/manifest ?

2022-09-28 08:40 UTC, WalrusB commented on basemodels/pydantic/manifest/data/groundtruth.py
> +SUPPORTED_CONTENT_TYPES = [
@alidzm validate_content_type is not the same as those Classes passed to exceptions are local. 
I would only move SUPPORTED_CONTENT_TYPES & JOB_TYPES_FOR_CONTENT_TYPE_VALIDATION.

2022-09-28 08:41 UTC, alidzm commented on basemodels/pydantic/manifest/data/groundtruth.py
> +SUPPORTED_CONTENT_TYPES = [
ok

2022-09-28 08:53 UTC, alidzm approved these changes

2022-09-28 10:23 UTC, igervasiychuk approved these changes

2022-10-04 08:19 UTC, emilimi commented on basemodels/manifest/manifest.py
> +from ..constants import JOB_TYPES_FOR_CONTENT_TYPE_VALIDATION
Let's not use relative imports

2022-10-04 08:25 UTC, emilimi commented on tests/both_models.py
> +    # TODO: FINISH THIS TEST
This may be related to how you import the mocked object. If you want to mock `basemodels.manifest.data.taskdata.validate_content_type` you need to import `basemodels.manifest.data.taskdata`

2022-10-10 12:51 UTC, posix4e commented
Good to merge

2022-10-11 07:32 UTC, merged